# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/david/Dropbox/Tesis/3DLuis/simulador_DDR_NO_SHADERS/simulador_full_openglv.4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/david/Dropbox/Tesis/3DLuis/simulador_DDR_NO_SHADERS/simulador_full_openglv.4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/Dropbox/Tesis/3DLuis/simulador_DDR_NO_SHADERS/simulador_full_openglv.4/CMakeFiles /home/david/Dropbox/Tesis/3DLuis/simulador_DDR_NO_SHADERS/simulador_full_openglv.4/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/Dropbox/Tesis/3DLuis/simulador_DDR_NO_SHADERS/simulador_full_openglv.4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

src/camera.o: src/camera.cpp.o
.PHONY : src/camera.o

# target to build an object file
src/camera.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/camera.cpp.o
.PHONY : src/camera.cpp.o

src/camera.i: src/camera.cpp.i
.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/camera.cpp.i
.PHONY : src/camera.cpp.i

src/camera.s: src/camera.cpp.s
.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/camera.cpp.s
.PHONY : src/camera.cpp.s

src/evader.o: src/evader.cpp.o
.PHONY : src/evader.o

# target to build an object file
src/evader.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/evader.cpp.o
.PHONY : src/evader.cpp.o

src/evader.i: src/evader.cpp.i
.PHONY : src/evader.i

# target to preprocess a source file
src/evader.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/evader.cpp.i
.PHONY : src/evader.cpp.i

src/evader.s: src/evader.cpp.s
.PHONY : src/evader.s

# target to generate assembly for a file
src/evader.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/evader.cpp.s
.PHONY : src/evader.cpp.s

src/objloader.o: src/objloader.cpp.o
.PHONY : src/objloader.o

# target to build an object file
src/objloader.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/objloader.cpp.o
.PHONY : src/objloader.cpp.o

src/objloader.i: src/objloader.cpp.i
.PHONY : src/objloader.i

# target to preprocess a source file
src/objloader.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/objloader.cpp.i
.PHONY : src/objloader.cpp.i

src/objloader.s: src/objloader.cpp.s
.PHONY : src/objloader.s

# target to generate assembly for a file
src/objloader.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/objloader.cpp.s
.PHONY : src/objloader.cpp.s

src/robot.o: src/robot.cpp.o
.PHONY : src/robot.o

# target to build an object file
src/robot.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/robot.cpp.o
.PHONY : src/robot.cpp.o

src/robot.i: src/robot.cpp.i
.PHONY : src/robot.i

# target to preprocess a source file
src/robot.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/robot.cpp.i
.PHONY : src/robot.cpp.i

src/robot.s: src/robot.cpp.s
.PHONY : src/robot.s

# target to generate assembly for a file
src/robot.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/robot.cpp.s
.PHONY : src/robot.cpp.s

src/sensorCamera.o: src/sensorCamera.cpp.o
.PHONY : src/sensorCamera.o

# target to build an object file
src/sensorCamera.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/sensorCamera.cpp.o
.PHONY : src/sensorCamera.cpp.o

src/sensorCamera.i: src/sensorCamera.cpp.i
.PHONY : src/sensorCamera.i

# target to preprocess a source file
src/sensorCamera.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/sensorCamera.cpp.i
.PHONY : src/sensorCamera.cpp.i

src/sensorCamera.s: src/sensorCamera.cpp.s
.PHONY : src/sensorCamera.s

# target to generate assembly for a file
src/sensorCamera.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/sensorCamera.cpp.s
.PHONY : src/sensorCamera.cpp.s

src/simulator.o: src/simulator.cpp.o
.PHONY : src/simulator.o

# target to build an object file
src/simulator.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/simulator.cpp.o
.PHONY : src/simulator.cpp.o

src/simulator.i: src/simulator.cpp.i
.PHONY : src/simulator.i

# target to preprocess a source file
src/simulator.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/simulator.cpp.i
.PHONY : src/simulator.cpp.i

src/simulator.s: src/simulator.cpp.s
.PHONY : src/simulator.s

# target to generate assembly for a file
src/simulator.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/simulator.cpp.s
.PHONY : src/simulator.cpp.s

src/transformation.o: src/transformation.cpp.o
.PHONY : src/transformation.o

# target to build an object file
src/transformation.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/transformation.cpp.o
.PHONY : src/transformation.cpp.o

src/transformation.i: src/transformation.cpp.i
.PHONY : src/transformation.i

# target to preprocess a source file
src/transformation.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/transformation.cpp.i
.PHONY : src/transformation.cpp.i

src/transformation.s: src/transformation.cpp.s
.PHONY : src/transformation.s

# target to generate assembly for a file
src/transformation.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/transformation.cpp.s
.PHONY : src/transformation.cpp.s

src/vector3D.o: src/vector3D.cpp.o
.PHONY : src/vector3D.o

# target to build an object file
src/vector3D.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vector3D.cpp.o
.PHONY : src/vector3D.cpp.o

src/vector3D.i: src/vector3D.cpp.i
.PHONY : src/vector3D.i

# target to preprocess a source file
src/vector3D.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vector3D.cpp.i
.PHONY : src/vector3D.cpp.i

src/vector3D.s: src/vector3D.cpp.s
.PHONY : src/vector3D.s

# target to generate assembly for a file
src/vector3D.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vector3D.cpp.s
.PHONY : src/vector3D.cpp.s

src/world.o: src/world.cpp.o
.PHONY : src/world.o

# target to build an object file
src/world.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/world.cpp.o
.PHONY : src/world.cpp.o

src/world.i: src/world.cpp.i
.PHONY : src/world.i

# target to preprocess a source file
src/world.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/world.cpp.i
.PHONY : src/world.cpp.i

src/world.s: src/world.cpp.s
.PHONY : src/world.s

# target to generate assembly for a file
src/world.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/world.cpp.s
.PHONY : src/world.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... rebuild_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/evader.o"
	@echo "... src/evader.i"
	@echo "... src/evader.s"
	@echo "... src/objloader.o"
	@echo "... src/objloader.i"
	@echo "... src/objloader.s"
	@echo "... src/robot.o"
	@echo "... src/robot.i"
	@echo "... src/robot.s"
	@echo "... src/sensorCamera.o"
	@echo "... src/sensorCamera.i"
	@echo "... src/sensorCamera.s"
	@echo "... src/simulator.o"
	@echo "... src/simulator.i"
	@echo "... src/simulator.s"
	@echo "... src/transformation.o"
	@echo "... src/transformation.i"
	@echo "... src/transformation.s"
	@echo "... src/vector3D.o"
	@echo "... src/vector3D.i"
	@echo "... src/vector3D.s"
	@echo "... src/world.o"
	@echo "... src/world.i"
	@echo "... src/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

